{% set name = "libavif" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AOMediaCodec/libavif/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bcd9a1f57f982a9615eb7e2faf87236dc88eb1d0c886f3471c7440ead605060d

build:
  run_exports:
    # TODO: Relax constraint when libavif >=1.0.0
    - {{ pin_subpackage('libavif', min_pin='x.x.x', max_pin='x.x.x') }}
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - nasm
    - ninja
    - meson
  host:
    - aom
    # - svt-av1  # TODO: linking error with this optional library

test:
  requires:
    - python >=3.6
  files:
    - check-exists.py
  commands:
    - python check-exists.py 10 0 0

about:
  home: https://github.com/AOMediaCodec/libavif
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A friendly, portable C implementation of the AV1 Image File Format
  description: |
    This library aims to be a friendly, portable C implementation of the AV1
    Image File Format, as described here
    <https://aomediacodec.github.io/av1-avif/>.

extra:
  recipe-maintainers:
    - carterbox
    - hmaarrfk
